name: Build & test image

on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      image-namespace:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      no-cache-filter:
        required: false
        type: string

jobs:
  build:
    name: Build & test image
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23
        with:
          detached: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Build and export locally to Docker
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          load: true
          tags: ${{ inputs.image-namespace }}/${{ inputs.image-repo }}:local-test
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache-filters: ${{ inputs.no-cache-filter }}
      - name: Install Test Kitchen
        uses: actionshub/chef-install@776a917c09d87c381d1d5342f83cd554223fa49c # 3.0.1
        env:
          # renovate: datasource=custom.omnitruck depName=chef-workstation
          CHEF_WS_VERSION: 25.9.1094
        with:
          project: chef-workstation
          version: ${{ env.CHEF_WS_VERSION }}
      - name: Prepare Test Kitchen
        env:
          CHEF_LICENSE: accept-silent
          # renovate: datasource=rubygems depName=kitchen-docker
          KITCHEN-DOCKER_VERSION: 3.0.0
        run: chef gem install kitchen-docker --version ${{ env.KITCHEN-DOCKER_VERSION }}
      - name: Run Test Kitchen
        run: kitchen test
